name: me
channels:
#  - postelrich
  - conda-forge
dependencies:
  - python>=3.6
  - numpy
  - simpleitk>2.0
  - matplotlib
  - scikit-image
  - pip
  - pywt
  - pip:
    - vtk
    - git+https://github.com/erosmontin/pynico
    - PyWavelets