[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
include = ["**/*.py"]

[project]
name = "pyable"
version = "3.0.1"
authors = [
  { name="Dr. Eros Montin, PhD", email="eros.montin@gmail.com" },
]
description = "Handy things you need for image analysis, at least I do."
readme = "README.md"
requires-python = ">=3.9"

dependencies = ["numpy","pynico @ git+https://github.com/erosmontin/pynico.git@v3","simpleitk>2.0","matplotlib","scikit-image","vtk","pandas"]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/erosmontin/pyable"
"Bug Tracker" = "https://github.com/erosmontin/pyable/issues"
