"""
VTK / SimpleITK conversion and ParaView export utilities for pyable.

This module provides:

- vtk2sitk:
    Convert vtkImageData into a SimpleITK image.

- sitk2vtk:
    Convert a 2D or 3D SimpleITK image into vtkImageData.

- sitk_to_structured_grid:
    Export scalar, vector, or tensor images as coordinate-aware
    vtkStructuredGrid objects.

- binary_mask_to_polydata:
    Convert a binary SimpleITK mask into a surface mesh.

- label_map_to_multiblock:
    Convert a multi-label segmentation into a VTK multiblock dataset,
    with one surface per label.

- write_vtk_dataset:
    Write .vts, .vtp, or .vtm files for ParaView.

Supported coordinate systems:

- "lps":
    Native SimpleITK physical coordinates.

- "ras":
    NIfTI-style RAS physical coordinates.

- "fsl":
    FSL scaled-voxel coordinates, useful when displaying images together
    with meshes generated by FSL tools.

- "index":
    Raw voxel indices.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable, Optional, Sequence

import numpy as np
import SimpleITK as sitk
import vtk
import vtk.util.numpy_support as vtknp
from vtk.util import numpy_support


# =============================================================================
# BASIC VTK <-> SIMPLEITK CONVERSION
# =============================================================================


def vtk2sitk(vtkimg: vtk.vtkImageData, debug: bool = False) -> sitk.Image:
    """
    Convert vtkImageData into a SimpleITK image.

    Scalar and multi-component VTK images are supported.

    Parameters
    ----------
    vtkimg:
        Input vtkImageData.
    debug:
        Print conversion details.

    Returns
    -------
    sitk.Image
        Converted SimpleITK image.
    """
    if not isinstance(vtkimg, vtk.vtkImageData):
        raise TypeError("vtk2sitk expects a vtkImageData object.")

    vtk_data = vtkimg.GetPointData().GetScalars()

    if vtk_data is None:
        vtk_data = vtkimg.GetPointData().GetVectors()

    if vtk_data is None:
        vtk_data = vtkimg.GetPointData().GetTensors()

    if vtk_data is None:
        raise ValueError(
            "VTK image has no active scalars, vectors, or tensors."
        )

    npdata = vtknp.vtk_to_numpy(vtk_data)

    nx, ny, nz = vtkimg.GetDimensions()
    ncomp = vtk_data.GetNumberOfComponents()

    if ncomp == 1:
        array = npdata.reshape((nz, ny, nx), order="C")
        sitkimg = sitk.GetImageFromArray(array, isVector=False)
    else:
        array = npdata.reshape((nz, ny, nx, ncomp), order="C")
        sitkimg = sitk.GetImageFromArray(array, isVector=True)

    sitkimg.SetSpacing(tuple(float(v) for v in vtkimg.GetSpacing()))
    sitkimg.SetOrigin(tuple(float(v) for v in vtkimg.GetOrigin()))

    if vtk.vtkVersion.GetVTKMajorVersion() >= 9:
        matrix = vtkimg.GetDirectionMatrix()

        if matrix is not None:
            direction = tuple(
                float(matrix.GetElement(row, col))
                for row in range(3)
                for col in range(3)
            )
            sitkimg.SetDirection(direction)

    if debug:
        print("VTK dimensions:", (nx, ny, nz))
        print("VTK components:", ncomp)
        print("NumPy shape:", npdata.shape)
        print("SimpleITK size:", sitkimg.GetSize())
        print("SimpleITK spacing:", sitkimg.GetSpacing())
        print("SimpleITK origin:", sitkimg.GetOrigin())
        print("SimpleITK direction:", sitkimg.GetDirection())

    return sitkimg


def sitk2vtk(
    img: sitk.Image,
    debugOn: bool = False,
    array_name: str = "values",
) -> vtk.vtkImageData:
    """
    Convert a 2D or 3D SimpleITK image into vtkImageData.

    Parameters
    ----------
    img:
        Input SimpleITK image.
    debugOn:
        Print conversion details.
    array_name:
        Name assigned to the VTK data array.

    Returns
    -------
    vtk.vtkImageData
        Converted VTK image.
    """
    if not isinstance(img, sitk.Image):
        raise TypeError("sitk2vtk expects a SimpleITK.Image.")

    if img.GetDimension() not in (2, 3):
        raise ValueError("sitk2vtk supports only 2D and 3D images.")

    size = list(img.GetSize())
    origin = list(img.GetOrigin())
    spacing = list(img.GetSpacing())
    direction = list(img.GetDirection())
    ncomp = int(img.GetNumberOfComponentsPerPixel())

    if img.GetDimension() == 2:
        size.append(1)
        origin.append(0.0)
        spacing.append(1.0)

        direction = [
            direction[0], direction[1], 0.0,
            direction[2], direction[3], 0.0,
            0.0,          0.0,          1.0,
        ]

    array = sitk.GetArrayFromImage(img)

    vtk_image = vtk.vtkImageData()
    vtk_image.SetDimensions(size)
    vtk_image.SetExtent(
        0, size[0] - 1,
        0, size[1] - 1,
        0, size[2] - 1,
    )
    vtk_image.SetSpacing(spacing)
    vtk_image.SetOrigin(origin)

    if vtk.vtkVersion.GetVTKMajorVersion() >= 9:
        vtk_image.SetDirectionMatrix(direction)
    elif debugOn:
        print("Warning: VTK < 9 cannot store a direction matrix.")

    if ncomp == 1:
        values = np.ascontiguousarray(array).ravel(order="C")
    else:
        values = np.ascontiguousarray(
            array.reshape(-1, ncomp, order="C")
        )

    vtk_array = numpy_support.numpy_to_vtk(
        values,
        deep=True,
    )
    vtk_array.SetName(array_name)

    vtk_image.GetPointData().SetScalars(vtk_array)
    vtk_image.Modified()

    if debugOn:
        print("VTK dimensions:", vtk_image.GetDimensions())
        print("VTK components:", vtk_array.GetNumberOfComponents())
        print("VTK origin:", vtk_image.GetOrigin())
        print("VTK spacing:", vtk_image.GetSpacing())

    return vtk_image


# =============================================================================
# COORDINATE TRANSFORMS
# =============================================================================


def get_voxel_to_space_matrix(
    image: sitk.Image,
    space: str = "lps",
) -> np.ndarray:
    """
    Return a 4x4 matrix mapping ITK voxel indices into a target space.

    Parameters
    ----------
    image:
        Three-dimensional SimpleITK image.
    space:
        One of "lps", "ras", "fsl", or "index".

    Returns
    -------
    np.ndarray
        4x4 affine matrix.
    """
    if image.GetDimension() != 3:
        raise ValueError(
            "Coordinate-aware ParaView export supports 3D images only."
        )

    space = str(space).lower()

    spacing = np.asarray(image.GetSpacing(), dtype=np.float64)
    origin = np.asarray(image.GetOrigin(), dtype=np.float64)
    direction = np.asarray(
        image.GetDirection(),
        dtype=np.float64,
    ).reshape(3, 3)

    voxel_to_lps = np.eye(4, dtype=np.float64)
    voxel_to_lps[:3, :3] = direction @ np.diag(spacing)
    voxel_to_lps[:3, 3] = origin

    if space == "lps":
        return voxel_to_lps

    if space == "ras":
        lps_to_ras = np.diag([-1.0, -1.0, 1.0, 1.0])
        return lps_to_ras @ voxel_to_lps

    if space == "index":
        return np.eye(4, dtype=np.float64)

    if space == "fsl":
        size = image.GetSize()

        voxel_to_fsl = np.diag(
            [
                spacing[0],
                spacing[1],
                spacing[2],
                1.0,
            ]
        )

        # FSL conditionally reverses the X axis for neurological storage.
        if np.linalg.det(voxel_to_lps[:3, :3]) > 0:
            voxel_to_fsl[0, 0] = -spacing[0]
            voxel_to_fsl[0, 3] = (size[0] - 1) * spacing[0]

        return voxel_to_fsl

    raise ValueError(
        f"Unknown coordinate space {space!r}. "
        "Choose 'lps', 'ras', 'fsl', or 'index'."
    )


def get_lps_to_space_linear_matrix(
    image: sitk.Image,
    space: str,
) -> np.ndarray:
    """
    Return the 3x3 linear transform from LPS vector components to target space.
    """
    voxel_to_lps = get_voxel_to_space_matrix(image, "lps")
    voxel_to_target = get_voxel_to_space_matrix(image, space)

    return (
        voxel_to_target[:3, :3]
        @ np.linalg.inv(voxel_to_lps[:3, :3])
    )


def transform_points(
    points_ijk: np.ndarray,
    matrix: np.ndarray,
) -> np.ndarray:
    """
    Apply a 4x4 affine matrix to an N-by-3 array of points.
    """
    points = np.asarray(points_ijk, dtype=np.float64)
    matrix = np.asarray(matrix, dtype=np.float64)

    if points.ndim != 2 or points.shape[1] != 3:
        raise ValueError("points_ijk must have shape (N, 3).")

    if matrix.shape != (4, 4):
        raise ValueError("matrix must have shape (4, 4).")

    homogeneous = np.column_stack(
        [
            points,
            np.ones(points.shape[0], dtype=np.float64),
        ]
    )

    return (homogeneous @ matrix.T)[:, :3]


# =============================================================================
# TENSOR HELPERS
# =============================================================================


def _tensor_components_to_matrices(values: np.ndarray) -> np.ndarray:
    """
    Convert tensor components into N-by-3-by-3 matrices.

    Supported layouts
    -----------------
    6 components:
        XX, XY, XZ, YY, YZ, ZZ

    9 components:
        Full row-major 3x3 matrix.
    """
    values = np.asarray(values)

    if values.ndim != 2:
        raise ValueError("Tensor values must have shape (N, components).")

    ncomp = values.shape[1]

    if ncomp == 9:
        return values.reshape(-1, 3, 3)

    if ncomp == 6:
        xx, xy, xz, yy, yz, zz = values.T

        tensors = np.empty(
            (values.shape[0], 3, 3),
            dtype=values.dtype,
        )

        tensors[:, 0, 0] = xx
        tensors[:, 0, 1] = xy
        tensors[:, 0, 2] = xz

        tensors[:, 1, 0] = xy
        tensors[:, 1, 1] = yy
        tensors[:, 1, 2] = yz

        tensors[:, 2, 0] = xz
        tensors[:, 2, 1] = yz
        tensors[:, 2, 2] = zz

        return tensors

    raise ValueError(
        "Tensor data must contain either 6 symmetric components "
        "or 9 full components."
    )


# =============================================================================
# STRUCTURED GRID EXPORT
# =============================================================================


def sitk_to_structured_grid(
    image: sitk.Image,
    space: str = "lps",
    stride: int = 1,
    array_name: str = "values",
    data_role: str = "scalars",
) -> vtk.vtkStructuredGrid:
    """
    Convert a 3D SimpleITK image into a coordinate-aware VTK structured grid.

    Parameters
    ----------
    image:
        Input 3D SimpleITK image.
    space:
        "lps", "ras", "fsl", or "index".
    stride:
        Spatial sampling step. A stride of 2 keeps every second voxel.
    array_name:
        Name assigned to the VTK data array.
    data_role:
        "scalars", "vectors", or "tensors".

    Returns
    -------
    vtk.vtkStructuredGrid
        ParaView-compatible structured grid.
    """
    if image.GetDimension() != 3:
        raise ValueError("Only 3D images are supported.")

    stride = max(1, int(stride))
    data_role = str(data_role).lower()

    if data_role not in {"scalars", "vectors", "tensors"}:
        raise ValueError(
            "data_role must be 'scalars', 'vectors', or 'tensors'."
        )

    array = sitk.GetArrayFromImage(image)

    if array.ndim not in (3, 4):
        raise ValueError(
            f"Unsupported array shape {array.shape}. "
            "Expected ZYX or ZYXC."
        )

    array = array[
        ::stride,
        ::stride,
        ::stride,
        ...,
    ]

    nz, ny, nx = array.shape[:3]

    i, j, k = np.meshgrid(
        np.arange(nx, dtype=np.float64) * stride,
        np.arange(ny, dtype=np.float64) * stride,
        np.arange(nz, dtype=np.float64) * stride,
        indexing="ij",
    )

    ijk = np.column_stack(
        [
            i.ravel(order="F"),
            j.ravel(order="F"),
            k.ravel(order="F"),
        ]
    )

    voxel_to_output = get_voxel_to_space_matrix(image, space)
    output_points = transform_points(ijk, voxel_to_output)

    vtk_points = vtk.vtkPoints()
    vtk_points.SetData(
        numpy_support.numpy_to_vtk(
            np.ascontiguousarray(
                output_points,
                dtype=np.float32,
            ),
            deep=True,
        )
    )

    grid = vtk.vtkStructuredGrid()
    grid.SetDimensions(nx, ny, nz)
    grid.SetPoints(vtk_points)

    # Scalar image: array shape is ZYX.
    if array.ndim == 3:
        if data_role != "scalars":
            raise ValueError(
                "A scalar image must use data_role='scalars'."
            )

        values = np.ascontiguousarray(
            array.ravel(order="C")
        )

        vtk_values = numpy_support.numpy_to_vtk(
            values,
            deep=True,
        )
        vtk_values.SetName(array_name)

        grid.GetPointData().SetScalars(vtk_values)

    # Multi-component image: array shape is ZYXC.
    else:
        ncomp = int(array.shape[-1])

        values = np.ascontiguousarray(
            array.reshape(-1, ncomp, order="C")
        )

        if data_role == "vectors":
            if ncomp != 3:
                raise ValueError(
                    "Vector data must have exactly 3 components."
                )

            if str(space).lower() != "lps":
                linear = get_lps_to_space_linear_matrix(
                    image,
                    space,
                )
                values = np.ascontiguousarray(
                    values @ linear.T
                )

            vtk_values = numpy_support.numpy_to_vtk(
                values,
                deep=True,
            )
            vtk_values.SetName(array_name)

            grid.GetPointData().SetVectors(vtk_values)

        elif data_role == "tensors":
            tensors = _tensor_components_to_matrices(values)

            if str(space).lower() != "lps":
                linear = get_lps_to_space_linear_matrix(
                    image,
                    space,
                )

                tensors = (
                    linear[None, :, :]
                    @ tensors
                    @ linear.T[None, :, :]
                )

            tensor_values = np.ascontiguousarray(
                tensors.reshape(-1, 9)
            )

            vtk_values = numpy_support.numpy_to_vtk(
                tensor_values,
                deep=True,
            )
            vtk_values.SetName(array_name)

            grid.GetPointData().SetTensors(vtk_values)

        else:
            vtk_values = numpy_support.numpy_to_vtk(
                values,
                deep=True,
            )
            vtk_values.SetName(array_name)

            grid.GetPointData().SetScalars(vtk_values)

    grid.Modified()
    return grid


# =============================================================================
# ROI AND LABEL-MAP SURFACE EXPORT
# =============================================================================


def binary_mask_to_polydata(
    image: sitk.Image,
    space: str = "lps",
    level: float = 0.5,
    smooth_iterations: int = 0,
    relaxation_factor: float = 0.1,
) -> vtk.vtkPolyData:
    """
    Convert a binary SimpleITK mask into a coordinate-aware surface mesh.

    Parameters
    ----------
    image:
        3D binary mask. Every value greater than zero is foreground.
    space:
        "lps", "ras", "fsl", or "index".
    level:
        Isosurface value.
    smooth_iterations:
        Number of optional windowed-sinc smoothing iterations.
        Use 0 to disable smoothing.
    relaxation_factor:
        Smoothing relaxation factor.

    Returns
    -------
    vtk.vtkPolyData
        Surface mesh.
    """
    if image.GetDimension() != 3:
        raise ValueError("binary_mask_to_polydata supports 3D masks only.")

    try:
        from skimage.measure import marching_cubes
    except ImportError as exc:
        raise ImportError(
            "scikit-image is required for surface export: "
            "pip install scikit-image"
        ) from exc

    mask = sitk.GetArrayFromImage(image) > 0

    if not np.any(mask):
        raise ValueError("Cannot create a surface from an empty mask.")

    padded = np.pad(
        mask.astype(np.uint8),
        pad_width=1,
        mode="constant",
        constant_values=0,
    )

    vertices_zyx, faces, _, _ = marching_cubes(
        padded,
        level=level,
    )

    # Remove the one-voxel padding offset.
    vertices_zyx -= 1.0

    # skimage returns ZYX vertices. Convert to ITK IJK = XYZ.
    vertices_ijk = vertices_zyx[:, [2, 1, 0]]

    voxel_to_output = get_voxel_to_space_matrix(image, space)
    vertices_xyz = transform_points(vertices_ijk, voxel_to_output)

    vtk_points = vtk.vtkPoints()
    vtk_points.SetData(
        numpy_support.numpy_to_vtk(
            np.ascontiguousarray(
                vertices_xyz,
                dtype=np.float32,
            ),
            deep=True,
        )
    )

    vtk_faces = vtk.vtkCellArray()

    for face in faces:
        triangle = vtk.vtkTriangle()
        triangle.GetPointIds().SetId(0, int(face[0]))
        triangle.GetPointIds().SetId(1, int(face[1]))
        triangle.GetPointIds().SetId(2, int(face[2]))
        vtk_faces.InsertNextCell(triangle)

    polydata = vtk.vtkPolyData()
    polydata.SetPoints(vtk_points)
    polydata.SetPolys(vtk_faces)

    clean = vtk.vtkCleanPolyData()
    clean.SetInputData(polydata)
    clean.Update()

    current_output = clean.GetOutput()

    if smooth_iterations > 0:
        smoother = vtk.vtkSmoothPolyDataFilter()
        smoother.SetInputData(current_output)
        smoother.SetNumberOfIterations(int(smooth_iterations))
        smoother.SetRelaxationFactor(float(relaxation_factor))
        smoother.FeatureEdgeSmoothingOff()
        smoother.BoundarySmoothingOn()
        smoother.Update()
        current_output = smoother.GetOutput()

    normals = vtk.vtkPolyDataNormals()
    normals.SetInputData(current_output)
    normals.AutoOrientNormalsOn()
    normals.ConsistencyOn()
    normals.SplittingOff()
    normals.Update()

    output = vtk.vtkPolyData()
    output.ShallowCopy(normals.GetOutput())
    return output


def label_map_to_multiblock(
    image: sitk.Image,
    labels: Optional[Sequence[int]] = None,
    space: str = "lps",
    smooth_iterations: int = 0,
    relaxation_factor: float = 0.1,
) -> vtk.vtkMultiBlockDataSet:
    """
    Convert a multi-label segmentation into one VTK surface per label.

    Parameters
    ----------
    image:
        Integer 3D label image.
    labels:
        Labels to export. If None, every non-zero label is exported.
    space:
        "lps", "ras", "fsl", or "index".
    smooth_iterations:
        Optional surface smoothing iterations.
    relaxation_factor:
        Optional surface smoothing relaxation factor.

    Returns
    -------
    vtk.vtkMultiBlockDataSet
        One vtkPolyData block per label.
    """
    if image.GetDimension() != 3:
        raise ValueError("label_map_to_multiblock supports 3D images only.")

    array = sitk.GetArrayFromImage(image)

    if labels is None:
        labels = [
            int(value)
            for value in np.unique(array)
            if int(value) != 0
        ]
    else:
        labels = [int(value) for value in labels if int(value) != 0]

    output = vtk.vtkMultiBlockDataSet()
    output.SetNumberOfBlocks(len(labels))

    for block_index, label_value in enumerate(labels):
        label_mask = sitk.Cast(
            sitk.Equal(image, label_value),
            sitk.sitkUInt8,
        )

        if sitk.GetArrayViewFromImage(label_mask).max() == 0:
            continue

        surface = binary_mask_to_polydata(
            label_mask,
            space=space,
            smooth_iterations=smooth_iterations,
            relaxation_factor=relaxation_factor,
        )

        label_array = numpy_support.numpy_to_vtk(
            np.full(
                surface.GetNumberOfPoints(),
                label_value,
                dtype=np.int32,
            ),
            deep=True,
        )
        label_array.SetName("label")
        surface.GetPointData().AddArray(label_array)

        output.SetBlock(block_index, surface)
        output.GetMetaData(block_index).Set(
            vtk.vtkCompositeDataSet.NAME(),
            f"label_{label_value}",
        )

    return output


# =============================================================================
# FILE WRITING
# =============================================================================


def write_vtk_dataset(dataset, output_path) -> str:
    """
    Write a VTK dataset using the correct XML writer.

    Supported outputs
    -----------------
    .vts:
        vtkStructuredGrid

    .vtp:
        vtkPolyData

    .vtm:
        vtkMultiBlockDataSet
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    suffix = output_path.suffix.lower()

    if suffix == ".vts":
        if not isinstance(dataset, vtk.vtkStructuredGrid):
            raise TypeError(".vts requires vtkStructuredGrid.")
        writer = vtk.vtkXMLStructuredGridWriter()

    elif suffix == ".vtp":
        if not isinstance(dataset, vtk.vtkPolyData):
            raise TypeError(".vtp requires vtkPolyData.")
        writer = vtk.vtkXMLPolyDataWriter()

    elif suffix == ".vtm":
        if not isinstance(dataset, vtk.vtkMultiBlockDataSet):
            raise TypeError(".vtm requires vtkMultiBlockDataSet.")
        writer = vtk.vtkXMLMultiBlockDataWriter()

    else:
        raise ValueError(
            "Unsupported extension. Use .vts, .vtp, or .vtm."
        )

    writer.SetFileName(str(output_path))
    writer.SetInputData(dataset)

    if writer.Write() != 1:
        raise IOError(f"Could not write VTK file: {output_path}")

    return str(output_path)
